### PR TITLE
Add Ubuntu Support

### PR DESCRIPTION
**Pull request by kjkeane**
This PR adds Ubuntu support, but also changes the use of the `os_family` grain to the `os` grain.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
The `os_family` grain supports Fedora, Amazon, RedHat, CentOS.   The `os` grain only supports RedHat afaik.

**Comment by aboe76** [comment]
@noelmcloughlin isn't it time to create something similar as the apache-formula:
```
osfingermap.yaml
osfamilymap.yaml
oscodenamemap.yaml
defaults.yaml
```

**Comment by aboe76** [comment]
@kjkeane can you take a look at the apache-formula and refactor the mapping?

**Comment by noelmcloughlin** [comment]
@aboe76  Not me surely :-o ... but yes apache is decent template ;-)

@kjkeane Sure, no problem but it might impact some people.

**Comment by kjkeane** [comment]
@aboe76 I can start looking at it tonight.  I will try to update this this weekend or Monday at the latest.

**Comment by aboe76** [comment]
@kjkeane no need to hurry

**Comment by kjkeane** [comment]
I have the changes ready, I was only able to test this out for RHEL 6, RHEL 7, and Ubuntu 18.04.  I am going to close this and recreate a new PR with the os mapping changes.

**Pull request closed without merging**
